# Deployment file for Azure Kubernetes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  selector:
    matchlabels:
      app: node-app
  replicas: 2 # no. of pods to run at a moment
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: rehaanmazid009/node-app
        ports:
        - containerPort: 80