version: "3"
services:
  nginx:
    ports:
      - "3001:80"

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      #bind mount
      - ./:/app
      #anonymous volume
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=test
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: npm run dev
  
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=password