version: "3"
services:
  nginx:
    ports:
      - "80:80"
  
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - SESSION_SECRET=${SESSION_SECRET}
    command: node app.js
    deploy: #docker swarm configuration for deployment
      replicas: 8 # no of containers up at a time instance
      restart_policy:
        condition: any 
      update_config:
        parallelism: 2 # no. of container to update at a time
        delay: 15s

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}