#This file is for things that are same between prod and dev
version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro  # create a bind mount for the nginx container image to use the custom config file

  node-app:
    build: .
    environment:
      - PORT=3000
    depends_on:
      - mongo

  mongo:
    # since we will directly use the image and dont
    # need to add anything to it, so instead of build
    # we will just use the image which in our case is
    # mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      # named volume (name:pathInContainer)
      # /data/db got from monogo dockers documentation
      - mongo-db:/data/db
  
  redis:
    image: redis

volumes:
  mongo-db: